version: '3.8'

services:
  web:
    build: 
      context: .
      args:
        - GITHUB_REPO=https://github.com/bikramadhikari001/synthenic.git
        - GITHUB_BRANCH=main
    container_name: synthenic_web_1
    networks:
      - synthenic_network
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    command: flask run --host=0.0.0.0 --port=8080

networks:
  synthenic_network:
    name: synthenic_network
